### PR TITLE
Lock version to <=3.1.6 until we can figure out what broke between th…

### PR DESCRIPTION
**Pull request by BjornTwachtmann**
…en and 3.2.1

### CODE REVIEW

**Comment by BjornTwachtmann** [comment]
Any objections to this until I can debug https://github.com/bbc/rmp-translate/issues/35 ?

**Comment by BPScott** [comment]
Did symfony backport those changes into the 2.x branch at any point?

**Comment by BjornTwachtmann** [comment]
Ugh, good point, looks like they did https://github.com/symfony/symfony/issues/18637

**Comment by spa-simone** [comment]
They backported into 2.X starting from v2.8.14

Assuming we define `en_GB` as fallback language and we define `cachepath`

**Version 2.8.13**
When `<lang>_GB` locale is requested, two files are generated: `<lang>_GB` and `en_GB`

**Version 2.8.14**
When `<lang>_GB` locale is requested, two files are generated: `<lang>_GB` and `<lang>` (which is empty). No `en_GB` file is created. If then `<lang>` is requested, since it is empty, it will fallback to english and generate both `en` and `en_GB`.

**Comment by spa-simone** [comment]
**v2.8.13 Example**
```
catalogue.ga.8739602554c7f3241958e3cc9b57fdecb474d508.php
catalogue.ga.8739602554c7f3241958e3cc9b57fdecb474d508.php.meta
catalogue.ga_GB.8739602554c7f3241958e3cc9b57fdecb474d508.php
catalogue.ga_GB.8739602554c7f3241958e3cc9b57fdecb474d508.php.meta
```

**v2.8.14 Example**
```
catalogue.en.8739602554c7f3241958e3cc9b57fdecb474d508.php
catalogue.en.8739602554c7f3241958e3cc9b57fdecb474d508.php.meta
catalogue.en_GB.8739602554c7f3241958e3cc9b57fdecb474d508.php
catalogue.en_GB.8739602554c7f3241958e3cc9b57fdecb474d508.php.meta
catalogue.ga.8739602554c7f3241958e3cc9b57fdecb474d508.php
catalogue.ga.8739602554c7f3241958e3cc9b57fdecb474d508.php.meta
catalogue.ga_GB.8739602554c7f3241958e3cc9b57fdecb474d508.php
catalogue.ga_GB.8739602554c7f3241958e3cc9b57fdecb474d508.php.meta
```

**Pull request closed without merging**
