### PR TITLE
Adding more needed translations for Rich Tracks

### PR DESCRIPTION
**Pull request by hammol04**
Hi @BjornTwachtmann , @djmarland , @BPScott

I have added more translations for Rich Tracks.

Please could I get a review.

Thank you

### CODE REVIEW

**Comment by djmarland** [comment]
:shipit:

**Comment by Jayflux** [comment]
:shipit:

**Comment by BPScott** [comment]
Should the translations be in alphabetical order, rather than us adding new things at the end? The rest of the file is alphabetical.

**Comment by hammol04** [comment]
I will go through all the files and make them alphabetical.

**Comment by hammol04** [comment]
Squashed and alphabeticalised.

**Comment by hammol04** [comment]
Please could I get another review? Thanks

**Comment by djmarland** [comment]
:+1:

**Pull request merged**
