### PR TITLE
Key with question mark removed.

### PR DESCRIPTION
**Pull request by pris54**
Key 'remove?' was deleted as it was causing problems.
Jira ticket: https://jira.dev.bbc.co.uk/browse/IPR-2536

### CODE REVIEW

**Comment by pris54** [comment]
@lehmam03 and @djmarland could you please review? Thank you.

**Comment by djmarland** [comment]
If you're happy not having the question mark in your front end page (as you've moved to just the word 'Remove' then this particular PR is fine

**Comment by pris54** [comment]
@djmarland yes, this is what we want.

**Comment by lehmam03** [comment]
:shipit:

**Pull request merged**
