### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by hammol04**
Please can I get squirrels!

I ran the alphabetiser so it looks like a few things got rearranged.

I've added..

Find us at, English, Welsh
All available episodes, English, Welsh 

Cheers

### CODE REVIEW

**Comment by djmarland** [comment]
:shipit:
:shipit: :shipit:
:shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit:
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit:
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit:
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit:
:shipit: :shipit: :shipit: :shipit: :shipit:
:shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit:
:shipit: :shipit:
:shipit:

**Comment by BjornTwachtmann** [comment]
I think you're missing the PO comments for a few of these

**Comment by hammol04** [comment]
Good spot @BjornTwachtmann and lol @djmarland !

**Comment by BjornTwachtmann** [comment]
:shipit: * ∞

**Pull request merged**
