### PR TITLE
Added translation for NHP -> MyRadioHeader Package

### PR DESCRIPTION
**Pull request by spa-simone**
English keys
1 overview
2 listen_List
3 following
4 added
5 last_chance
6 latest
7 a-z
 
Welsh (cy)
1 Trosolwg
2 Rhestr Wrando
3 Yn Dilyn
4 Ychwanegwyd
5 Cyfle Olaf
6 Diweddaraf
7 A-Z
 
Gaeilge (ga)
1 Forléargas
2 Liosta Éisteachta
3 Á Leanúint Agat
4 Curtha Leis
5 Deis Dheireanach
6 Is Déanaí
7 A-Z
 
Gàidhlig (gd)
1 Tar-shealladh
2 Liosta Èisteachd
3 A’ leantainn
4 Air a chur ris
5 Cothrom mu dheireadh
6 As ùire
7 A-Z

### CODE REVIEW

**Comment by BjornTwachtmann** [comment]
Two things.

One, you need to run the updateTranslationsFromTemplate script and commit the files it updates.

Two are these for use in Amen? Or is NHP using the programmes domain directly?

**Comment by spa-simone** [comment]
* I've run "updateTranslationsFromTemplate"
* At the moment they are used in the Favourites/Follows header page only. I've asked @djmarland who suggested to add them to "programme" namespace.

**Comment by djmarland** [comment]
Radio already has a fair few things in the "programmes" space. At some point we have to put some effort in to split this out correctly (as well as dealing with "shared". That doesn't have to be right now

**Comment by spa-simone** [comment]
I don't mind helping in splitting the Radio bits, once we decide it is time to do it.

**Comment by BjornTwachtmann** [comment]
Okay, just wondered if this was Amen stuff as we now have an "amen" domain. As it's not, feel free to merge 👍

**Pull request merged**
