### PR TITLE
Translations for recently played text

### PR DESCRIPTION
**Pull request by pris54**
Welsh = Chwaraewyd yn ddiweddar
Scottish Gaelic = Air a chluich o chionn gohirid
Irish = Seinnte le gairid

### CODE REVIEW

**Comment by pris54** [comment]
@Jayflux could you please review? Thanks.

**Comment by pris54** [comment]
@shashikantjagtap could you please review? Thanks.

**Comment by hammol04** [comment]
Hi Paula,

Translations look good :)

We will also have to add empty translations for the rest of the language files.

Similair to this: https://github.com/bbc/rmp-translate/blob/master/src/RMP/Translate/lang/programmes/my.po#L114

Including programmes.pot as well :) (And alphabetical, as you've already done!)

Thank you,
Laurence

**Comment by pris54** [comment]
@hammol04 thanks for the review. We already have empty entries for the rest of the languages, that was done and merged some time ago.

**Comment by BjornTwachtmann** [comment]
@hammol04 This is already in the template, https://github.com/bbc/rmp-translate/blob/master/src/RMP/Translate/lang/programmes/programmes.pot#L1366 . The code looks fine. I'm assuming you've double checked the actual translations, so feel free to merge.

**Comment by hammol04** [comment]
Okay in that case, looks good :shipit:

**Comment by shashikantjagtap** [comment]
@pris54 Changes looks alright to me. I would suggest to get an author of this library @BjornTwachtmann to verify it won't break anything else. I hope it won't impact anything else

**Pull request merged**
