### PR TITLE
Added amen default translation domain and parametised scripts to run on specified domain

### PR DESCRIPTION
**Pull request by stephenrobertsuk**
…ltiple domains

### CODE REVIEW

**Comment by BPScott** [comment]
When recieving updated translations we use `updateLanguageFromSuppliedPO` to pull in new changes. I highly doubt we'd ever give people a source PO file to complete that contains information from multiple domains - in fact we'd end up giving them the po from a specific domain. This I don't think it makes sense to loop that over all domains - instead we'd need to teach it an additional argument where the user specifies the domain that they want to merge changes into

**Comment by djmarland** [comment]
There's a lingering task here to create some sort of "shared" translations list, that the other translations inherit from (though that's not possible at the moment).
Everything in Amen will have to be in that "shared" list or you risk not having a translation available when you try to use an object.

At the moment the shared one appears to be the "programmes" one, even though the naming is wrong.

**Comment by BjornTwachtmann** [comment]
This looks fine. I haven't tested it, but that's pretty much what I was talking about. Do you still want to add the trAmen function to the translate helper to default to the amen domain? It's worth having that at least until I can get round to https://github.com/bbc/rmp-translate/issues/23 .

**Comment by stephenrobertsuk** [comment]
Were you invisioning that helper method exist here or would that not go in the amen codebase (i.e. in https://github.com/bbc/rmp-amen/blob/master/lib/src/RMP/Amen/Extension/RMPTranslateExtension.php)?

**Comment by BjornTwachtmann** [comment]
Yeah, that's the one. Looks like you've already done that, so ignore me :)

**Comment by BjornTwachtmann** [comment]
Please have a squirrel. Or any small furry animal of your choice to signify approval.

**Comment by BPScott** [comment]
:shipit: Looks good, we can tidy up the readme to talk about "hey there are multiple domains" and what that means later.

**Comment by jucke** [comment]
:shipit:

**Pull request merged**
