### PR TITLE
IPR-2006 - On Air Translation

### PR DESCRIPTION
**Pull request by pris54**
On Air package, part of 'Track now playing'
Translation for key 'last_played'

More details in Jira:
https://jira.dev.bbc.co.uk/browse/IPR-2006

### CODE REVIEW

**Comment by BjornTwachtmann** [comment]
This looks fine code-wise. Sorry to be pedantic here, but is it necessary to add a new priority class called "Track Now Playing". These are only used in rmp-translate-tool as a guide to editorial, and I'd like to keep the number down as the dropdown list is full enough already.

**Comment by djmarland** [comment]
You didn't follow the instructions that I sent. There should be many more files changed than this if you run the script as directed and it should be in the right place alphabetically.
And as Bjorn says, it doesn't need a new priority value

**Comment by djmarland** [comment]
:+1:

**Comment by BPScott** [comment]
LGTM :shipit:

**Pull request merged**
